# DEFAULT SWAGREET CONFIGURATION

### ASSETS

# directory containing the assets (CSS, icons, and the background image)
assets_dir = "/etc/greetd/swagreet/assets"

### MAXIMUM ATTEMPTS

# maximum attempts before the user has to wait for the timeout
# - e.g. 3 means the user is locked out after failing to enter the correct password 3 times
# - use 0 to disable
maximum_attempts = 3

# how long the user has to wait after failing the password check too many times
maximum_attempts_timeout_seconds = 60

### MONITORS

# the priortiy of monitors the login window should be shown on
# - values further in the list will be used if earlier ones are not available.
# - other monitors will still show the background image
monitor_order = ["WL-1", "DP-1", "HDMI-A-1"]

### USERS

# Leave commented if you want to automatically detect AccountService users

# users = [
#     { name = "example_1", avatar_path = "/path/to/avatar_1.png" },
#     { name = "example_2", avatar_path = "/path/to/avatar_2.png" },
# ]

### SESSIONS

# list of session names to ignore
# - these will not be displayed in the session menu
# ignored_sessions = ["Hyprland", "GNOME"]
